import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Support Genius",
  description:
    "Learn how Support Genius collects, uses, stores, and protects information submitted through this website and support inquiry forms.",
};

export default function PrivacyPolicy() {
  const sections = [
    {
      num: "01",
      title: "Information we collect",
      content:
        "We may collect information you choose to provide, such as your name, work email address, company name, app or website URL, support requirements, ticket-volume information, and messages you send through our forms or email. We may also collect technical and usage information generated by your use of the website, such as IP address, browser type, device information, pages viewed, referral source, and approximate location, depending on the tools we actually use.",
    },
    {
      num: "02",
      title: "How we use information",
      bullets: [
        "Respond to inquiries, schedule discussions, and assess whether our services may be a fit.",
        "Operate, secure, troubleshoot, and improve the website and our service process.",
        "Understand how visitors find and use the website, where permitted and consistent with applicable law.",
        "Comply with legal obligations, enforce agreements, and protect our rights, users, and services.",
      ],
    },
    {
      num: "03",
      title: "How we share information",
      content:
        "We may share information with service providers that help us host the website, operate forms, schedule meetings, analyze website performance, communicate with you, or provide related business services. We may also disclose information when required by law or to protect rights, safety, and security. We do not sell personal information in exchange for money.",
    },
    {
      num: "04",
      title: "Cookies and analytics",
      content:
        "We use essential cookies to ensure the proper functionality of our website. Where enabled, privacy-respecting analytics measure general site usage without tracking personal identities across third-party websites. You can configure your browser to decline cookies, though certain interactive features of the website may function with limited convenience.",
    },
    {
      num: "05",
      title: "Data retention and security",
      content:
        "We retain personal information only for as long as reasonably necessary for the purposes described in this policy, unless a longer period is required or permitted by law. We use reasonable administrative, technical, and organizational safeguards appropriate to our business and the information we handle. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.",
    },
    {
      num: "06",
      title: "Your choices and rights",
      content:
        "Depending on where you live, you may have rights to request access, correction, deletion, or restriction of certain personal information, or to object to certain processing. To make a request, contact privacy@thesupportgenius.com. We may need to verify your identity before responding.",
    },
    {
      num: "07",
      title: "Contact and changes",
      content:
        "For questions about this Privacy Policy or our privacy practices, contact Support Genius at privacy@thesupportgenius.com or via our contact page. We may update this policy from time to time. When we do, we will change the effective date and, where required, provide additional notice.",
    },
  ];

  return (
    <main className="min-h-screen text-ink bg-canvas pb-20">
      {/* Hero Section */}
      <section className="section-hero pt-14 pb-12 sm:pt-18 sm:pb-16 lg:pt-20 lg:pb-20 border-b border-hairline-cool">
        <div className="mx-auto max-w-[860px] px-5 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-canvas-soft border border-hairline text-xs font-medium text-ink mb-6">
            <span className="status-dot-green" />
            <span>Legal &amp; Privacy Trust</span>
          </div>

          <h1 className="display-xxl text-ink">
            Privacy Policy
          </h1>

          <div className="mt-4 flex items-center justify-center gap-2 text-xs font-mono uppercase tracking-wider text-ink-mute">
            <svg
              className="w-3.5 h-3.5 text-primary"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
              />
            </svg>
            <span>Effective date: September 1, 2026</span>
          </div>

          {/* Lead Intro Box */}
          <div className="mt-8 p-6 sm:p-7 rounded-xl border border-hairline bg-canvas-soft text-left">
            <p className="body-lg text-ink leading-relaxed">
              Support Genius (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;) respects your privacy. This Privacy
              Policy explains how we collect, use, disclose, and protect personal information when you visit
              our website, contact us, or submit an inquiry about our Shopify app support services.
            </p>
          </div>
        </div>
      </section>

      {/* Structured Modular Sections */}
      <section className="mx-auto max-w-[860px] px-5 sm:px-6 lg:px-8 py-12 sm:py-16 space-y-6 sm:space-y-8">
        {sections.map((sec) => (
          <div
            key={sec.num}
            className="card-feature-light p-6 sm:p-8 rounded-xl border border-[#dfdfdf]"
          >
            <span className="spotlight-glow" />

            {/* Card Header with Section Badge */}
            <div className="flex items-center gap-3 mb-4">
              <span className="text-xs font-mono font-bold text-primary bg-[#3ecf8e]/10 border border-[#3ecf8e]/20 px-2.5 py-1 rounded-md">
                {sec.num}
              </span>
              <h2 className="text-[19px] sm:text-[22px] font-medium text-ink tracking-tight">
                {sec.title}
              </h2>
            </div>

            {/* Paragraph Content */}
            {sec.content && (
              <p className="body-md text-ink-mute leading-relaxed text-[15px] sm:text-[16px]">
                {sec.content}
              </p>
            )}

            {/* Bullet Points Grid */}
            {sec.bullets && (
              <div className="grid gap-3 sm:grid-cols-2 mt-2">
                {sec.bullets.map((b, bIdx) => (
                  <div
                    key={bIdx}
                    className="flex items-start gap-3 p-3.5 rounded-lg bg-canvas-soft border border-hairline-cool"
                  >
                    <span className="status-dot-green mt-1.5 shrink-0" />
                    <span className="text-sm text-ink-mute leading-relaxed">
                      {b}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>
        ))}

        {/* Bottom Conversion & Navigation Card */}
        <div className="mt-12 p-8 rounded-xl card-feature-dark text-white flex flex-col sm:flex-row items-center justify-between gap-6">
          <span className="spotlight-glow" />
          <div>
            <h3 className="heading-lg text-white">
              Questions about our privacy policy?
            </h3>
            <p className="mt-1 body-sm text-ink-faint">
              Reach out to our operations team for any data requests or clarifications.
            </p>
          </div>
          <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto shrink-0">
            <Link
              href="/"
              className="btn-secondary py-2.5 px-5 text-sm text-center justify-center"
            >
              Return to home page
            </Link>
            <Link
              href="/contact"
              className="btn-primary py-2.5 px-5 text-sm text-center justify-center"
            >
              Contact our team
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}